### PR TITLE
Obey .ssh/config

### PR DESCRIPTION
**Pull request by pento**
See #23.

TODO:

- [x] Method to return `Hostname`
- [x] Method to return `User`
- [x] Method to return `IdentitiesOnly`
- [x] Method to return `IdentityFile`
- [x] Method to return `ServerAliveInterval`

### CODE REVIEW

**Comment by pento** [comment]
@thingalon: Any other ssh config directives you use? I'm not going to bother implementing the entire ssh config spec, just the parts that we use.

Also, tag anyone you know who still uses PonyEdit, and may be interested in this feature.

**Comment by thingalon** [comment]
I also use `ServerAliveInterval`. Other than that, you've got the full set I use.

**Comment by pento** [comment]
@thingalon: Heads up, I've re-arranged the project quite a bit in this PR. I figured a new, independent class was a good thing to start writing tests for, and best practice for QTests seems to be as part of a `subdir` project. I might shuffle things around a bit more, but the general gist is that most of the repo has been move to the `src` directory, to live alongside the `tests` directory.

If you happen to recall any other best practices for this from your Qt experience, feel free to jump in. :-)

See the [recent Travis run](https://travis-ci.org/PonyEdit/PonyEdit/jobs/268395758#L922) for an example of test output.

**Comment by pento** [comment]
Note: I'd originally intended to add support for `AddKeysToAgent` and `UseKeychain`, so that keys would be automatically added to the agent, but libssh2 doesn't support writing to the agent, only reading.

**Pull request merged**
